# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Flask application

on:
  push:
    branches: [ "setup-GithubAction-with-docker-container" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: traveltunes:latest
    - name: Test
      run: |
        docker run -d -p 5000:5000 traveltunes:latest
        sleep 5 # Donne un peu de temps au conteneur pour démarrer
        curl --retry 10 --retry-delay 5 -v http://127.0.0.1:5000/
    
    #    - name: Test with pytest
#      run: |
#        pytest
